name: encryption_server
description: HTTP сервер для шифрування/розшифрування повідомлень з RSA та AES-GCM

version: 1.0.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  pointycastle: ^3.7.3

dev_dependencies:
  lints: ^2.1.0